// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR35EPMgTlWpU78EL9yxQd6d9QzfTZ1Oc',
    appId: '1:669774477950:web:3277357f5842dbaf69762f',
    messagingSenderId: '669774477950',
    projectId: 'edutech-43b01',
    authDomain: 'edutech-43b01.firebaseapp.com',
    storageBucket: 'edutech-43b01.appspot.com',
    measurementId: 'G-0D4R0QLBJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQrRkThqlK0Qt5loHUCJGZFR1yGAovbQ',
    appId: '1:669774477950:android:721cb33a1579c73d69762f',
    messagingSenderId: '669774477950',
    projectId: 'edutech-43b01',
    storageBucket: 'edutech-43b01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgyLPbBpeJgmmg58UAsnsoskM7ZM7BzWE',
    appId: '1:669774477950:ios:0b2fcda1701eede869762f',
    messagingSenderId: '669774477950',
    projectId: 'edutech-43b01',
    storageBucket: 'edutech-43b01.appspot.com',
    iosBundleId: 'com.example.edutech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgyLPbBpeJgmmg58UAsnsoskM7ZM7BzWE',
    appId: '1:669774477950:ios:bfd6f5ccbc78f2cc69762f',
    messagingSenderId: '669774477950',
    projectId: 'edutech-43b01',
    storageBucket: 'edutech-43b01.appspot.com',
    iosBundleId: 'com.example.edutech.RunnerTests',
  );
}
